version: '3'

services:

  database:
    image: mariadb:${MARIADB_VERSION}
    container_name: db_sf_recipes
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ${DB_NAME:-sf_recipes}
      MYSQL_USER: ${DB_USER:-sfuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-sfuser1234}
    networks:
      - sf_recipe_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_sf_recipes
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - sf_recipe_network

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app_sf_recipes
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - database
    networks:
      - sf_recipe_network
    environment:
      DB_HOST: database
    volumes:
      - ./:/var/www

networks:
  sf_recipe_network:

volumes:
  db-data:
